-- سكريبت SQL لإصلاح جدول العملاء في قاعدة بيانات PostgreSQL
-- يضيف خاصية IDENTITY لعمود id لتوليد الأرقام تلقائياً

-- التحقق من وجود جدول customers وإضافة IDENTITY إلى عمود id
DO $$
DECLARE
    is_identity_enabled BOOLEAN;
    has_sequence BOOLEAN;
    column_default TEXT;
    table_exists BOOLEAN;
BEGIN
    -- التحقق من وجود جدول customers
    SELECT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'customers'
    ) INTO table_exists;
    
    IF table_exists THEN
        RAISE NOTICE 'جدول العملاء موجود';
        
        -- التحقق من حالة عمود id
        SELECT 
            c.is_identity = 'YES',
            c.column_default,
            c.column_default LIKE '%nextval%'
        INTO 
            is_identity_enabled,
            column_default,
            has_sequence
        FROM 
            information_schema.columns c
        WHERE 
            c.table_schema = 'public' 
            AND c.table_name = 'customers' 
            AND c.column_name = 'id';
            
        RAISE NOTICE 'حالة عمود id الحالية:';
        RAISE NOTICE 'is_identity: %', CASE WHEN is_identity_enabled THEN 'YES' ELSE 'NO' END;
        RAISE NOTICE 'column_default: %', column_default;
        RAISE NOTICE 'has_sequence: %', CASE WHEN has_sequence THEN 'YES' ELSE 'NO' END;
        
        -- إصلاح العمود إذا لم يكن مهيأ بالفعل
        IF NOT is_identity_enabled AND NOT has_sequence THEN
            RAISE NOTICE 'جاري إضافة IDENTITY إلى عمود id...';
            
            ALTER TABLE customers 
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            
            RAISE NOTICE 'تم إضافة IDENTITY إلى عمود id بنجاح';
            
            -- التحقق من التغيير
            SELECT 
                c.is_identity = 'YES',
                c.column_default
            INTO 
                is_identity_enabled,
                column_default
            FROM 
                information_schema.columns c
            WHERE 
                c.table_schema = 'public' 
                AND c.table_name = 'customers' 
                AND c.column_name = 'id';
                
            RAISE NOTICE 'حالة عمود id بعد التعديل:';
            RAISE NOTICE 'is_identity: %', CASE WHEN is_identity_enabled THEN 'YES' ELSE 'NO' END;
            RAISE NOTICE 'column_default: %', column_default;
        ELSE
            RAISE NOTICE 'عمود id مهيأ بالفعل، لا حاجة للتعديل';
        END IF;
    ELSE
        RAISE NOTICE 'جدول العملاء غير موجود!';
    END IF;
END $$;

-- اختبار إدراج سجل جديد للتأكد من عمل التوليد التلقائي
DO $$
DECLARE
    is_identity_enabled BOOLEAN;
    new_id INTEGER;
BEGIN
    -- التحقق من أن IDENTITY مفعل
    SELECT c.is_identity = 'YES'
    INTO is_identity_enabled
    FROM information_schema.columns c
    WHERE c.table_schema = 'public' 
    AND c.table_name = 'customers' 
    AND c.column_name = 'id';
    
    IF is_identity_enabled THEN
        -- إدراج سجل اختباري
        INSERT INTO customers (name, phone)
        VALUES ('عميل اختباري', '0000000000')
        RETURNING id INTO new_id;
        
        RAISE NOTICE 'تم إدراج سجل اختباري بنجاح مع معرف: %', new_id;
        
        -- حذف السجل الاختباري
        DELETE FROM customers WHERE id = new_id;
        RAISE NOTICE 'تم حذف السجل الاختباري';
    END IF;
END $$;