-- SQL script to fix customers.id column in PostgreSQL
-- Run this directly in Railway PostgreSQL console

-- Check if customers table exists
DO $$
BEGIN
  IF EXISTS (
    SELECT FROM information_schema.tables 
    WHERE table_schema = 'public' 
    AND table_name = 'customers'
  ) THEN
    -- Check if id column has IDENTITY
    IF NOT EXISTS (
      SELECT FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'customers' 
      AND column_name = 'id'
      AND is_identity = 'YES'
    ) THEN
      -- Fix the column by adding IDENTITY
      ALTER TABLE customers 
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
      
      RAISE NOTICE 'Successfully added IDENTITY to customers.id column';
    ELSE
      RAISE NOTICE 'customers.id already has IDENTITY configured';
    END IF;
  ELSE
    RAISE NOTICE 'Customers table does not exist!';
  END IF;
END $$;