-- سكريبت SQL لإصلاح عمود customers.id في قاعدة بيانات Railway
-- يمكن تنفيذه مباشرة في وحدة تحكم SQL على Railway

-- التحقق من وجود جدول customers وإضافة IDENTITY إلى عمود id
DO $$
DECLARE
    is_identity_enabled BOOLEAN;
    has_sequence BOOLEAN;
    column_default TEXT;
BEGIN
    -- التحقق من وجود جدول customers
    IF EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'customers'
    ) THEN
        RAISE NOTICE 'جدول العملاء موجود';
        
        -- التحقق من حالة عمود id
        SELECT 
            c.is_identity = 'YES',
            c.column_default,
            c.column_default LIKE '%nextval%'
        INTO 
            is_identity_enabled,
            column_default,
            has_sequence
        FROM 
            information_schema.columns c
        WHERE 
            c.table_schema = 'public' 
            AND c.table_name = 'customers' 
            AND c.column_name = 'id';
            
        RAISE NOTICE 'حالة عمود id الحالية:';
        RAISE NOTICE 'is_identity: %', CASE WHEN is_identity_enabled THEN 'YES' ELSE 'NO' END;
        RAISE NOTICE 'column_default: %', column_default;
        RAISE NOTICE 'has_sequence: %', CASE WHEN has_sequence THEN 'YES' ELSE 'NO' END;
        
        -- إصلاح العمود إذا لم يكن مهيأ بالفعل
        IF NOT is_identity_enabled AND NOT has_sequence THEN
            RAISE NOTICE 'جاري إضافة IDENTITY إلى عمود id...';
            
            ALTER TABLE customers 
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            
            RAISE NOTICE 'تم إضافة IDENTITY إلى عمود id بنجاح';
        ELSE
            RAISE NOTICE 'عمود id مهيأ بالفعل، لا حاجة للتعديل';
        END IF;
    ELSE
        RAISE NOTICE 'جدول العملاء غير موجود!';
    END IF;
END $$;